# Generated by Django 5.0.4 on 2024-04-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.user'),
        ),
    ]
